
CREATE TABLE Lista 
( 
 Id INT PRIMARY KEY AUTO_INCREMENT,  
 Nome VARCHAR(n) NOT NULL,  
 Data DATE NOT NULL  
); 

CREATE TABLE Tarefa 
( 
 Id INT PRIMARY KEY AUTO_INCREMENT,  
 Nome VARCHAR(n) NOT NULL,   
 idLista INT,  
); 

ALTER TABLE Tarefa ADD FOREIGN KEY(idLista) REFERENCES Lista (Id)
